//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace SvnBridge.Properties
{
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    sealed partial class Settings : ApplicationSettingsBase
    {
        static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));

        public static Settings Default
        {
            get { return defaultInstance; }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.WebServiceUrl)]
        [DefaultSettingValue("https://tfs01.codeplex.com/Services/v1.0/Registration.asmx")]
        public string SvnFacade_Library_RegistrationWebSvc_Registration
        {
            get { return ((string)(this["SvnFacade_Library_RegistrationWebSvc_Registration"])); }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.WebServiceUrl)]
        [DefaultSettingValue("https://tfs01.codeplex.com/VersionControl/v1.0/repository.asmx")]
        public string SvnFacade_Library_RepositoryWebSvc_Repository
        {
            get { return ((string)(this["SvnFacade_Library_RepositoryWebSvc_Repository"])); }
        }
    }
}